import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import AuthModalProviderWrapper from '@/components/AuthModal/AuthModalProvider';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <AuthModalProviderWrapper>{children}</AuthModalProviderWrapper>
      </body>
    </html>
  );
}
