import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import AuthModalProviderWrapper from '@/components/Modals/AuthModal/AuthModalProvider';
import ToastProvider from '@/components/ToastProvider/ToastProvider';
import { UserProvider } from '@/contexts/UserContext';
import UserMenuProviderWrapper from '@/components/Modals/UserMenuModal/UserMenuProvider';
import ConfirmLogoutProviderWrapper from '@/components/Modals/ConfirmLogoutModal/ConfirmLogoutProvider';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <UserProvider>
          <ConfirmLogoutProviderWrapper>
            <UserMenuProviderWrapper>
              <AuthModalProviderWrapper>
                <ToastProvider>{children}</ToastProvider>
              </AuthModalProviderWrapper>
            </UserMenuProviderWrapper>
          </ConfirmLogoutProviderWrapper>
        </UserProvider>
      </body>
    </html>
  );
}
